# Generated by Django 5.2.8 on 2026-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_appointment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
