# Generated by Django 5.2.8 on 2026-01-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_labreport_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='amount',
        ),
        migrations.AddField(
            model_name='labreport',
            name='observed_value',
            field=models.CharField(blank=True, help_text='e.g. 7.3 mg/dL', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='reference_range',
            field=models.CharField(blank=True, help_text='e.g. 10-20 mg/dL', max_length=100, null=True),
        ),
    ]
