# Generated by Django 5.2.8 on 2026-01-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_labreport_amount_labreport_observed_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='file_url',
        ),
        migrations.AddField(
            model_name='labreport',
            name='clinical_interpretation',
            field=models.TextField(blank=True, help_text='Actionable insights and medical context', null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='specimen_type',
            field=models.CharField(blank=True, default='Serum', max_length=100),
        ),
        migrations.AddField(
            model_name='labreport',
            name='testing_method',
            field=models.CharField(blank=True, default='Fully Automated Biochemistry Analyzer', max_length=100),
        ),
    ]
