# Generated by Django 5.2.8 on 2026-01-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_labreport_date_remove_labreport_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g. mg/dL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='observed_value',
            field=models.CharField(blank=True, help_text='e.g. 7.3', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='reference_range',
            field=models.CharField(blank=True, help_text='e.g. 10-20', max_length=100, null=True),
        ),
    ]
