# Generated by Django 5.2.8 on 2026-01-06 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_labreport_unit_alter_labreport_observed_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labreport',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
    ]
