# Generated by Django 5.2.8 on 2026-01-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vitals',
            field=models.TextField(blank=True, help_text='JSON or text of vitals (BP, Temp, Weight)', null=True),
        ),
    ]
