# Generated by Django 5.2.8 on 2026-01-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_appointment_diagnosis_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
