# Generated by Django 6.0.1 on 2026-01-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_appointment_decline_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='medical_history',
            field=models.TextField(blank=True, help_text='e.g. Allergies to peanuts, Asthma', null=True),
        ),
    ]
