# Generated by Django 5.2.8 on 2026-02-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_user_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text="Doctor's consultation fee", max_digits=10),
        ),
    ]
