# Generated by Django 5.2.8 on 2026-03-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('normal', 'Normal Consultation'), ('online', 'Online Consultation')], default='normal', max_length=20),
        ),
    ]
